### ISSUE TITLE
Convert to string

### ISSUE THREAD

**Issue by no-treasure** [0tii/html-to-pdf#1]
How i can convert html to pdf-string?
When i do
```
const buffer = await html2pdf('<h1>Test</h1>', { fileType: 'buffer', viewPort: '1000x700' })
return buffer.toString()
```
and then from CLI
```
node ./index.js >> my-doc.pdf
```
if i open the document it will be empty

**Comment by no-treasure** [comment]
@0tii

**Comment by 0tii** [comment]
> @0tii

Piping a buffer string representation (`buffer.toString()`) to a .pdf file like you did is probably not producing a correct pdf, as the buffer bytes have to be written to the file, not the string representation of the buffer. You can use the native `fs.writeFileSync()´ to write the buffer to a pdf file.

You can also write to pdf file using either `base64ToPdf()` or `bufferToPdf()` functions exported from the module or by using the [`path` option](https://github.com/0tii/html-to-pdf/blob/master/options.md#path), all of which internally also use `fs.writeFileSync()`

**Comment by no-treasure** [comment]
@0tii  But i need a string, no way how i can do this? react-pdf has function `renderToString`, and it works

**Comment by 0tii** [comment]
> 

`fileType: 'base64'` returns the file content encoded as a base64 string. That will still not create a valid pdf if piped to a file. What exactly do you need to do so that your pdf needs to be a string?

**Comment by no-treasure** [comment]
I want to write CLI-app, that take json from agruments and return pdf, i don't need to write file

**Comment by 0tii** [comment]
> I wont to write CLI-app, that take json from agruments and return pdf, i don't need to write file

for file content string representations i am offering `base64` fileType. Your specification is unclear because if you don't need to write the pdf to a file what do you need the string representation for, when you could use the binary buffer instead and save unnecessary conversions?
